### ISSUE TITLE
Difference between regional prompter extension and proposed complementary regional diffusion

### ISSUE THREAD

**Issue by ShashwatNigam99** [YangLing0818/RPG-DiffusionMaster#8]
I was trying to understand if there is any difference between [hako-mikan's popular regional prompter extension](https://github.com/hako-mikan/sd-webui-regional-prompter) and the "complementary regional diffusion" strategy proposed in this work?
I see that the code to perform attention/latent coupling under the /scripts folder is the same.

**Comment by YangLing0818** [comment]
Thanks for your comments. Our complementary regional diffusion does not have to set up the regions / parameters manually. More importantly, the "complementary regional diffusion" is a broader concept because we also use it to conduct image editing based on the planned **complementary contours**. For better understanding, you can refer to the image editing part in our paper and we will release the code of this part in the near future.
